### ISSUE TITLE
Return type for extreme concatenate

### ISSUE THREAD

**Issue by dennisrall** [laike9m/Python-Type-Challenges#115]
In your solution to the extreme concatenate problem you propose:
```python
def transform[T, **P](f: Callable[Concatenate[Any, P], T]):
    def wrapper(value: Person, *args: P.args, **kwargs: P.kwargs) -> T:
        return f(value, *args, **kwargs)

    return wrapper
```

But if I add the return type of `Callable[Concatenate[Person, P], T]` to the transform function, the test in line 19 fails.

Is there a better return type or do you recommend skipping it in general?

**Comment by laike9m** [comment]
Thanks for reporting this issue.

Though, it looks to me to be expected behavior. Note that `foo2` is defined as:

```python
def foo2(value, mode: str, *, maybe: bool) -> int:
    return 1
```

which is not equivalent to `Callable[Concatenate[Person, P], T]`, because this type annotation misses the "keyword only" constraint. As of today, I don't think Python's type-system supports it.

**Comment by dennisrall** [comment]
Thanks for the fast response and the great project.

What do you think about adding a hint that the return type should be omitted?

**Comment by laike9m** [comment]
> Thanks for the fast response and the great project.
> 
> What do you think about adding a hint that the return type should be omitted?

Sure, fine with me. Feel free to make a PR and I'll approve.

**Comment by akatsukilelouch** [comment]
> Taking it back. I tend to think this is a bug of pyright, or due to some inherent restriction of Python's type system. On our side, not sure there's much we can do.

`ParamSpec` loses information on keyword variables when they're altered in any way (neither `Concatenate` construction nor `ParamSpec` has any syntax to extract and insert keyword arguments; that could look like `Concatenate[Keyword[Literal["name"], T], P]` or something).

It can't be expressed in type annotations only, hence the only way is to rely on the type checker to infer the returning type.

See https://typing.python.org/en/latest/spec/generics.html#paramspec-variables at the end:

> There are still some classes of decorators still not supported with these features:
>
> * those that add/remove/change a variable number of parameters (for example, functools.partial remains untypable even using ParamSpec)
> * those that __add/remove/change keyword-only parameters.__

**Comment by Tatsh** [comment]
I sure wish the challenge stated that putting the return type was not required. I had everything correct except for the kwargs-only test failing due to adding a return type `Callable[Concatenate[Person, P], T]`.
