### ISSUE TITLE
The example in `docs/Contribute.md` may be a little wrong

### ISSUE THREAD

**Issue by NCBM** [laike9m/Python-Type-Challenges#15]
![Screenshot_20231102_184619](https://github.com/laike9m/Python-Type-Challenges/assets/37037264/9b7e8672-1757-46ec-97b5-ab48c1bf8ad3)

`dict[str: str]` does not seem to be correct, and it should be `dict[str, str]`.

![Screenshot_20231102_184819](https://github.com/laike9m/Python-Type-Challenges/assets/37037264/2ea4aaca-4f25-42d2-936c-4453a472769d)
![Screenshot_20231102_185012](https://github.com/laike9m/Python-Type-Challenges/assets/37037264/79adbaa4-2b2f-4eb9-a02e-eeaec468546d)
![Screenshot_20231102_185744](https://github.com/laike9m/Python-Type-Challenges/assets/37037264/d982fd23-90f4-44da-95f0-f689a48be7ec)

**Comment by laike9m** [comment]
Thanks, fixed
