### ISSUE TITLE
Two challenges can't pass under mypy (and maybe more)

### ISSUE THREAD

**Issue by laike9m** [laike9m/Python-Type-Challenges#18]
https://github.com/RF-Tar-Railt/Python-Type-Challenges/blob/main/challenges/advanced-overload-generic/question.py

https://github.com/RF-Tar-Railt/Python-Type-Challenges/blob/main/challenges/extreme-constructor-parameter/question.py

**mypy**
<img width="1491" alt="image" src="https://github.com/laike9m/Python-Type-Challenges/assets/2592205/efec658d-79f9-4d26-9b8a-dec87e9ccf59">

**pyright** only reports errors in test code, which is what we expected

<img height="400" alt="image" src="https://github.com/laike9m/Python-Type-Challenges/assets/2592205/4d96741b-18b8-445e-8178-553ce584cdd7">

This issue should be fixed once we migrate to pyright (#9)

cc @RF-Tar-Railt @frostming

**Comment by RF-Tar-Railt** [comment]
应该是overload装饰的原函数类型没写全（

**Comment by laike9m** [comment]
Switched to pyright fixed the issue. Closing.
