### ISSUE TITLE
Challenge should include Python target version

### ISSUE THREAD

**Issue by yanyongyu** [laike9m/Python-Type-Challenges#2]
Python version will affect the challenge test, such as:

Challenge - dict

```python
type custom = dict[str, str]

def foo(x: custom):
    pass
```

it's ok in python 3.12, but could not pass the test.

![image](https://github.com/laike9m/Python-Type-Challenges/assets/42488585/4e10794d-e596-459f-a59d-830acccb2ff2)

**Comment by laike9m** [comment]
Thanks for the feedback. Will add some information 

Though this is because mypy doesn't support it yet
https://github.com/python/mypy/issues/15238

**Comment by yanyongyu** [comment]
[Pyright](https://github.com/microsoft/pyright), which developed by the author of the issue you mentioned, has already supported this feature. It's also a modern static type checker supported by microsoft and used in vscode officially. It could also set the python version and even platform type. Here's an playground [example](https://pyright-play.net/?code=C4TwDgpgBAxgrgZ2AewLZQLxQCYEsbADaSATgDRSkC6AUDdhAGZSPLIAUAHgFyyIqoAlNxpQxUMAEMECOiQgA3CJIA2AfVCR2rZIJpA).

![image](https://github.com/laike9m/Python-Type-Challenges/assets/42488585/560012f3-4d19-4b78-910c-6da26794d24e)

**Comment by laike9m** [comment]
You're right, I'm considering supporting more type checkers (pyright in particular) as a long term solution, since pyright implements the typing PEPs more timely.

In the short-term, I plan to add some message to indicate the things that are not yet supported (like the `type` keyword)

**Comment by yanyongyu** [comment]
For some complex type derivation challenges, we have encountered many situations that mypy cannot infer, and Pyright is able to do so. That's good if pyright will be supported.

**Comment by laike9m** [comment]
ture. Unfortunately mypy is not well funded as pyright does, as you can imagine
