### ISSUE TITLE
Feature: provide python version switch

### ISSUE THREAD

**Issue by yanyongyu** [laike9m/Python-Type-Challenges#27]
pyright supports switch python version with command line option `--pythonversion`

**Comment by laike9m** [comment]
It's not hard to add, but I question the value it brings. It also complicates things, as some challenges may not be able to pass with old Python versions.

**Comment by yanyongyu** [comment]
Provide python version switch may make python developers familiar with the compatibility and syntax of different python versions.

**Comment by laike9m** [comment]
> Provide python version switch may make python developers familiar with the compatibility and syntax of different python versions.

That's true, but IMO the complexity and maintenence burden it adds overweighs the value it brings. Besides, people can always use old syntax in newer version of Python, and the type checker would happily make it pass. So at least for now, this is not on the roadmap.

**Comment by laike9m** [comment]
Thanks for understanding.
