### ISSUE TITLE
Feature request: allow resetting user code to its original form

### ISSUE THREAD

**Issue by nobod4t** [laike9m/Python-Type-Challenges#29]
Scenario:
  I write some codes, it does not work so I want to start over again. I want to remove all my code quickly and start from the original codes.

**Comment by laike9m** [comment]
Good idea, something I didn't think of. We could definitely add it!

**Comment by 100gle** [comment]
Good requirement. Let me add a reset button for editor later.

**Comment by laike9m** [comment]
> Good requirement. Let me add a reset button for editor later.

Thanks!
