### ISSUE TITLE
Errors in running "Challenge - concatenate"

### ISSUE THREAD

**Issue by skilldeliver** [laike9m/Python-Type-Challenges#61]
Hello, 
I was trying to solve the last challenge.
[this one](https://python-type-challenges.zeabur.app/extreme/concatenate)

but I was getting strange errors in the output, so
I decided to test out the [real solution](https://github.com/laike9m/Python-Type-Challenges/blob/main/challenges/extreme-concatenate/solution.py#L10C1-L22C19) but again, pasting & running the solution produced errors:

![image](https://github.com/laike9m/Python-Type-Challenges/assets/37806520/1f43f1a2-f62a-4027-b9f2-c26d32815243)

**Comment by laike9m** [comment]
Hmm, I can't reproduce it. Could you post a screenshot of the failure, with code you typed on the left? thanks

**Comment by laike9m** [comment]
Closed, but feel free to reopen.
