### ISSUE TITLE
Add `from typing import *` to boilerplate

### ISSUE THREAD

**Issue by georgeh** [laike9m/Python-Type-Challenges#62]
I imagine that imports were left out to avoid giving clues, but it would be nice to have all the type hints imported into the namespace.

**Comment by laike9m** [comment]
I tend to not add it, given `import *` is discouraged in the first place. Also writing the import is just a few characters typing..

**Comment by laike9m** [comment]
Plus, there are things you don't need to import, like tuple, dict, list, etc; and things are better imported from `collections.abc` instead of typing.
