### ISSUE TITLE
Allow custom challenge order

### ISSUE THREAD

**Issue by piglei** [laike9m/Python-Type-Challenges#73]
Currently the challenges appear in alphabetical order, it would be better if we customize the order by prioritizing the easier challenges to the top. For example, the basic challenges could use this order:

```
# The basic syntax
- parameter
- return
- variable
- any
- kwargs
# Composite data types
- list
- dict
- tuple
# Other
- typealias
- union
- optional
- final
```

This would make the experience better as people go through the challenges from top to bottom.

**Comment by laike9m** [comment]
Agree this can be improved, but not at the cost of extra complexity. It seems that to change the order, we would always need to store it somewhere else, which is a no-go to me.

**Comment by piglei** [comment]
> Agree this can be improved, but not at the cost of extra complexity. It seems that to change the order, we would always need to store it somewhere else, which is a no-go to me.

Yes, the order has to be stored somewhere, at least we might need to use flask's project `Config' object. One approach might be this:

- Introduce a project config variable: `challenge_order: List[challenge name]`.
- When getting challenges, use the above list as an index.
- If the challenge is missing from the index, put it to the bottom and use alphabetical order.
- This means that if `challenge_order` is empty, the system would work normally as well.

**Comment by laike9m** [comment]
Thanks for proposing the solution. Though it may change in the future, at this point, I don't think this is something worth adding.

**Comment by piglei** [comment]
OK. I would love to contribute if you change your mind in the future. 😁
