### ISSUE TITLE
Define the criterias for determing a challenge's level

### ISSUE THREAD

**Issue by laike9m** [laike9m/Python-Type-Challenges#8]
Right now there are 4 levels
- basic
- intermediate
- advanced
- extreme

Though there's no predefined criterias for determing a challenge's level.

**Comment by frostming** [comment]
Several criteria I can think of:

- The simplicity of the reference solution
- The commonality of the pattern in development
- The number of examination points
- The popularity of the typing primitives used by the reference solution

**Comment by aka-phrankie** [comment]
初级:升级标准:掌握基础数据结构和可调用性

any # 最简单类型注解
list # 常用内置容器类型,需要理解基础数据结构
dict # 常用内置映射类型,需要理解键值对映射关系
tuple # 不可变容器类型,理解不可变性
callable # 需要理解函数和可调用性

中级:升级标准:掌握函数参数和返回值注解的定义

optional # 理解可选参数的使用
parameter # 掌握参数注解的定义
return # 掌握返回值注解的定义
literal # 理解字面量类型的使用
union # 理解联合类型的使用

高级:升级标准:掌握类、函数和泛型的高级用法

decorator # 需要理解函数装饰器
class-var # 需要理解类和类属性
instance-var # 需要理解实例和实例属性
overload # 需要理解方法重载
protocol # 需要理解协议和抽象类型
recursive # 需要理解递归函数和数据类型
self # 需要理解实例方法中的self
typeguard # 需要实现类型保护
generic # 需要掌握泛型的定义和使用
generic-param # 需要掌握泛型参数的定义
generic-with-constraints # 需要掌握有约束的泛型

按照最小知识量提升原则让claude排布的，但是感觉高级里面还是太密了，请有工程实践经验的人再优化排布😊。

**Comment by laike9m** [comment]
我觉得可以加一个 `extreme` 类别，区分于 advanced。

> * The commonality of the pattern in development

感觉 commonality 和 popularity 不是特别好判断

**Comment by laike9m** [comment]
Closed. I think a formal criteria is probably unnecessary.
