### ISSUE TITLE
The ellipsis in the function parameters of challenge intermediate/literalstring causes challenge failed

### ISSUE THREAD

**Issue by b1indsight** [laike9m/Python-Type-Challenges#81]
In challenge intermediate/literalstring, function `execute_query` has a parament accepted `Iterable[str]`，and set default value `...`. The same pattern is observed in the provided [solution](https://github.com/laike9m/Python-Type-Challenges/blob/main/challenges/intermediate-literalstring/solution.py).
```python
def execute_query(sql, parameters: Iterable[str] = ...):
    """No need to implement it"""
``` 
This will cause a type check error by pyright
> error: Expression of type "ellipsis" cannot be assigned to parameter of type "Iterable[str]"

It seems like I must access type check by changing `Iterable[str]` to `Iterable[str] | EllipsisType` , like

```python
from typing import Iterable, LiteralString
from types import EllipsisType


def execute_query(sql: LiteralString, parameters: Iterable[str] | EllipsisType = ...):
    """No need to implement it"""
```

or change `...` to  `()` for type check.

```python
from typing import Iterable, LiteralString
from types import EllipsisType


def execute_query(sql: LiteralString, parameters: Iterable[str] = ()):
    """No need to implement it"""
```

I don't think either of the above solutions to be the best way for this issue, but I don't know any better way to use ellipsis for default parameter with type hint.

**Comment by laike9m** [comment]
May I ask which type checker are you using? Python-Type-Challenges uses pyright and it works as expected, see [playground](https://pyright-play.net/?code=EQhQBUHkBFILlKAmgewK4HIBOBTABAO5YCWALsQHYDmeAhoTgEZ6O0DGA1jhQCYB0oAIIUKKUrVL56AMzQU25FBTwADHAA8cbNJID6ARzQ4sATxWEAFsTYW8WOQGc8AZQCKAGQA0LHXQA2Dih4bLTKAA64AG7cpC4eeJQAVlqKyhLinA4CIMCI0lgoALZ4pCZhlDTEhWEoWLHuZMa0fs6kJNTeAJKSWLSMfjiIoDw40ngaWjo4BkamABQO%2Bn5weA09za3tVN5htL2FOD0OK91N-TgA2g5tALp4ALx4fM8AlAh4H0-PQwDEP3gAUV4eBQYxM6CwwRQIzwf2GozwhmMJl0aAcxjmaOMumIPBW1ywb1An0RsxMDzw0mAzgB7gBAGFwHgAFR4ABiACVIABZPA8CT0ADqAAkARyAXgsVgcTwKQBvKUygC%2BuRJE20eiR8y1JheH3%2BGjCKQAtKUjcbjAUsEMRmMdbp%2BeJMejpbj8W1vH4qmQVowUCg-HrjQA%2BPAAOSUOHenx1FJyxJJnxpdMZCcTialfAotAOnjT6c%2BmdoVEGBfZXN5jto%2BZJIrFEsVuIpAH58-H88Qxl7Cj6azGyXgANSPYCrTrczpMgCMuXz6qmM2Rcx13md2NxnheLyAA). It is normal that different type checkers behave differently here and there.

`parameters: Iterable[str] = ()` works too, if you make a PR I'll accept it.

**Comment by b1indsight** [comment]
I'm using Pyright version 1.1.344, which you can reproduce in this [playground](https://pyright-play.net/?code=EQhQBUHkBFILlKAmgewK4HIBOBTABAO5YCWALsQHYDmeAhoTgEZ6O0DGA1jhQCYB0oAIIUKKUrVL56AMzQU25FBTwADHAA8cbNJID6ARzQ4sATxWEAFsTYW8WOQGc8AZQCKAGQA0LHXQA2Dih4bLTKAA64AG7cpC4eeJQAVlqKyhLinA4CIMCI0lgoALZ4pCZhlDTEhWEoWLHuZMa0fs6kJNTeAJKSWLSMfjiIoDw40ngaWjo4BkamABQO%2Bn5weA09za3tVN5htL2FOD0OK91N-TgA2g5tALp4ALx4fM8AlAh4H3g5AHJBFDg4HglIJVMIDA4UWJkHJDADEsLwAFFeHgUGMTOgsMEUCM8PDhqM8IZjCZdGgHMY5uTjLpiDwVtcsG9QJ8ibMTA88NJgM5Ee5EQBhcB4ABUeAAYgAlSAAWTwPAk9AA6gAJRGSxF4alYWlAx4Ab21uoAvrlWRNtHpifNrSYXh8ERowikALSlZ0u4wFLBDEZjW26BXiKkUnV0hltbx%2BKpkFaMFAoPz2l0APjwv3%2B70%2Bts5MNZrN5-KFLPzpe1fAotAOnhLpdZ5doVEGdYl0rlQdotfzqvVmqNdM5AH4uzCu8QxtHCrGu6ycwBqR7AVadGWdYUARlyXYtUxmJLmtu8IZpdM8LxeQA).

I found a related discussion in this [issue](https://github.com/microsoft/pyright/issues/5985) of pyright and the corresponding  [release note](https://github.com/microsoft/pyright/releases/tag/1.1.329) of version 1.1.329.  The key change mentioned is:

> Behavior Change: Added check for the use of an ellipsis for a default argument value for a function that is not in a stub, not overloaded, and without a placeholder implementation.

---
When an ellipsis is used in a function body, means not been implemented, Pyright treats the ellipsis as Any, for example:
```python
from typing import LiteralString, Iterable
def execute_query(sql: LiteralString, parameters: Iterable[str] = ...):
     ...
``` 
will get:
```shell
> pyright --pythonversion=3.12  test.py
0 errors, 0 warnings, 0 informations 
```
When using docstring, `pass`, and `NotImplementedError`,  Pyright will check the type of ellipsis used as a default parameter. This behavior causes the type check error.
```python
from typing import LiteralString, Iterable
def execute_query(sql: LiteralString, parameters: Iterable[str] = ...):
    """Not implemented yet."""
```
```shell
>  pyright --pythonversion=3.12  test.py
test.py:3:67 - error: Expression of type "ellipsis" cannot be assigned to parameter of type "Iterable[str]"
    "ellipsis" is incompatible with protocol "Iterable[str]"
      "__iter__" is not present (reportGeneralTypeIssues)
1 error, 0 warnings, 0 informations 
```
---
I think adding an ellipsis within the function `execute_query`'s body of [question file](https://github.com/laike9m/Python-Type-Challenges/blob/59d0cb4a12f7b6591a5c6b40387235101c04ff10/challenges/intermediate-literalstring/question.py#L12) is a better way to fix this. The solution file can pass the type check (I made a mistake for this).

**Comment by laike9m** [comment]
Thanks for digging into this. You're right about the current behavior (this comment [describes](https://github.com/microsoft/pyright/issues/5985#issuecomment-1729351826) it).

I'll make a change to question.py to use ellipsis in function body.
