### ISSUE TITLE
extreme-concatenate not working? (maybe outdated pyright)

### ISSUE THREAD

**Issue by asottile** [laike9m/Python-Type-Challenges#82]
this works locally -- and on the version of pyright stated in requirements.txt

<summary>spoilers

<details>

```python
from typing import Protocol


class Person:
    pass


class P1[R, **P](Protocol):
    def __call__(self, value: object, *args: P.args, **kwargs: P.kwargs) -> R: ...

class P2[R, **P](Protocol):
    def __call__(self, value: Person, *args: P.args, **kwargs: P.kwargs) -> R: ...

def transform[R, **P](f: P1[R, P]) -> P2[R, P]:
    def wrapper(value: Person, *args: P.args, **kwargs: P.kwargs) -> R:
        return f(value, *args, **kwargs)

    return wrapper
```

</details>
</summary>

peeked at the stated solution and it feels a little cheeky to rely on the type checker to fill in the return value there

**Comment by asottile** [comment]
found out what's happening -- in the pyright playground it is not inferencing the reassignment of `foo_with_person` -- renaming the second one to `foo_with_person2` fixes the puzzle output

no idea why it's different locally though

**Comment by laike9m** [comment]
I checked the [playground](https://pyright-play.net/?pyrightVersion=1.1.346&code=EQhQBUHkBFILlKAygVwA5oPYGcCmACAFwAtcAnXAcm3wEN8AzFAOwGNCBLTZ-AAwcyZeAGnwB3YjgIMOZbIXxpaZWgFtchcvla0eAIwK6AniQ7MA5gDpEATUwpxuhYUz4UePgKGi9KBWKciVwp5Mg52IlJGWXk6MnMUdWZnVwM6PgAFcmxuXms7Bx1mZkwFVUwAEw4GI09BEXwc-CN7fArcVg52oPEwzXSmNk5uPkIVZmwBMlURUBciccnMabqhfDN5kmkWdi4eFocA5OsQYERQBjJMVSIjNDNzddUsMgUMq5dWTAAbRFZv2jYGhZOTcBD4CGKQHYP4AoH4DIARgA2gAlUQAKgxGQAugAKd6lTBfb4ASnBkPaDHwAH0aTpvt86Xi8N8GKIAG60b4oXBwfCYPQAKw6hExynM2H5GUsEuwmIxAGsAvEpQjLMq5aT8ABaAB8%2BFR-MsJth0IRACY0QrcQSPsSfuTQJC2rhqXSGUyaSzcGzOdzedLstxxarpbLVQrNWH1dHJdr9YbjabQFSFroltNrfgsbaGNKUeiETiEwaMlai7iKRC02IVBhyHiuTy%2BQjg8xQ5Lw3Koyqu7G%2B9hS0nnS7IRRCCgyDwGE2A7hO-Kc0rB6TEC6J1OeHXaA2yIg0145y3ROV2vzQsOAHLcPmjiFKIHnLw0sQcEg0tDt-AAXnTEymVQ8S8NcXzfD8v1BZgCXbPFSVEYBEWAUDBFfd9iE-WCQRyaD4PwM9cB-RDkIuVDwIwyCcLxREEKQ7V8AAYnwXAAA8v3YHVCDuXAdXIK59zA9DMKgmCRLwxF6KY1j2MITjuN4sh%2BNIzA0IgrDYLw4jRAtSTmLY0U5K-BSlIPN1GEEC1j15U9KlbUJMVPWgjAMfk9EEMldQNDZq3wTdp3wRFnzIoTKJGP8xgzQDgIslCVPI4SqOw7g4No4BHOcwjwDIXlYtUijYObXkfyS3CbPaIikPSgwfyynLlLyhLkpKlL8Nsiq0vwpzqtq3Bcvi0LoOavCCPa3TpIMrijL45Z6v69SxNEGjOoymrst6iEpP0jjJp46aBOCtSRKG1KqsIiSNr0mTDN2xSZsEw7Eo0k78B6sattknbjJmoA) with your code, it seems to work as expected?

<img width="792" alt="image" src="https://github.com/laike9m/Python-Type-Challenges/assets/2592205/5b5f1870-30b6-427f-b80b-3a80ef42c77b">

**Comment by asottile** [comment]
very strange -- indeed appears to pass now \o/
