### ISSUE TITLE
Too easy to pass `extreme-variance`

### ISSUE THREAD

**Issue by F-park** [laike9m/Python-Type-Challenges#89]
## Description

```py
def f(a: list[int | str]):
    pass


def g(a: str | list):
    pass
```

![image](https://github.com/laike9m/Python-Type-Challenges/assets/52167622/df87dda2-a464-4859-be3d-f2c2a29a02db)

## Suggestion

Maybe we can use [definition](https://docs.python.org/3/glossary.html#term-sequence) to make challenge strict.

**Comment by laike9m** [comment]
Could you clarify a bit on the modification?

**Comment by F-park** [comment]
> Could you clarify a bit on the modification?

```py
"""
TODO: Annotate function `foo`, to make tests pass.
"""
from collections.abc import Sequence


def foo(args: Sequence[int | str]):
    pass


## End of your code ##
foo(1)  # expect-type-error
foo("1")
foo(b"1")
foo([1, "2"])
foo((1, "2", *[3 for _ in range(233)]))
foo({1})  # expect-type-error
```

**Comment by laike9m** [comment]
Thanks! Tested it and it did solve the issue. I'll make a PR.

Also, I didn't know bytes is actually represented as a sequence of int, learned something new :)

**Comment by F-park** [comment]
It is still too easy to pass the challenge.

```
def f(a: list[int | str]):
    pass


def g(a: str | bytes | list | tuple):
    pass
```

![image](https://github.com/laike9m/Python-Type-Challenges/assets/52167622/3dabf950-115b-43db-b8f5-d61722a0c457)

**Comment by laike9m** [comment]
Enabling strict mode would break other challenges, and I don't want to enable it since most people likely don't enable it.

Thinking twice, the current checks are not perfect but should be good enough. `g((1, "2", *(3 for _ in range(233))))` doesn't seem to provide much value? at least it doesn't guard against `str | tuple | bytes | list`.
