### ISSUE TITLE
Switch to use pyright

### ISSUE THREAD

**Issue by GreyElaina** [laike9m/Python-Type-Challenges#9]

**Comment by laike9m** [comment]
It's on the roadmap.

**Comment by yanyongyu** [comment]
Something may be useful:

Pyright playground server: https://github.com/erictraut/pyright-playground

<details><summary>--mypy ++pyright</summary>
<p>

Mypy: !!!!!

![image](https://github.com/laike9m/Python-Type-Challenges/assets/42488585/547f64fa-5523-4959-9fbd-a52424ea2432)

</p>
</details>

**Comment by laike9m** [comment]
I've been using pyright-playground during development tool, it's very handy. I also plan to add a link to it for every challenge, with code automatically populated, so people can use pyright-playground's language server & autocomplete (which we are not likely to provide here )

**Comment by laike9m** [comment]
I'm starting to work on it, and hopefully to get it done this weekend

**Comment by laike9m** [comment]
Have switched to pyright, closed.
