### ISSUE TITLE
Enable UTF-8 mode for python (PEP 686)

### ISSUE THREAD

**Issue by F-park** [laike9m/Python-Type-Challenges#92]
## Description

After `pdm dev`, `UnicodeDecodeError`(gbk: illegal multibyte sequence) caused by string `——` 

the string is in `Python-Type-Challenges/challenges/intermediate-self/hints.md`

---

Also, the emoji cannot load successfully
![ba39653952033119fc57dcda2a265726](https://github.com/laike9m/Python-Type-Challenges/assets/52167622/27062a39-9640-4990-99b4-93a161c83ca9)

## Solution

[Python UTF-8 mode](https://docs.python.org/3/library/os.html#python-utf-8-mode)

**Comment by 100gle** [comment]
🤔 很奇怪，我现在 Chrome 里打开已经部署在 zeabur 似乎没有发现这个问题，在 mac 上运行启动命令时好像也没有见 `UnicodeDecodeError` 这个错误，你这个错误是在 Windows 上运行而导致的吗？

**Comment by laike9m** [comment]
See if it fixes the problem.

Could be that Windows is using GBK (or something else) as the default encoding.

**Comment by F-park** [comment]
> 🤔 很奇怪，我现在 Chrome 里打开已经部署在 zeabur 的版本似乎没有发现这个问题，在 mac 上运行启动命令时好像也没有见 `UnicodeDecodeError` 这个错误，你这个错误是在 Windows 上运行或IDE自动修改编码而导致的吗？

参考[语言区域编码格式](https://docs.python.org/zh-cn/3/glossary.html#term-locale-encoding)，不同系统会有不一样的行为。

我是 Windows 上运行的，没改过 IDE 或编码，通过 scoop 下载的 python。
