### ISSUE TITLE
[Web] 500 Internal Server Error

### ISSUE THREAD

**Issue by F-park** [laike9m/Python-Type-Challenges#97]
## Description

When I click the button online, the server return a 500 error.
![image](https://github.com/laike9m/Python-Type-Challenges/assets/52167622/d09b016f-62e3-4b74-aef8-e2c48e26cc90)
![image](https://github.com/laike9m/Python-Type-Challenges/assets/52167622/a05d55e3-0dff-447a-a710-70d7e958667b)

---

However, I can run locally, it seems not error for python.
Or 84551ad9c1d668a9aecfa73ebac25faa81a9cb3c cause?

**Comment by laike9m** [comment]
Thanks for catching it! Looks like this is an issue with Zeabur, as it changes to serverless deployment (from containerized deployment). I'll ask them how to fix it.

**Comment by laike9m** [comment]
Filed a ticket for Zeabur

https://discord.com/channels/1060209568820494336/1197939687629791345

**Comment by laike9m** [comment]
Fixed by reverting to containerized deploy by forcing `FORCE_CONTAINERIZED=1`
